name: Report a Bug
description: The game crashed or something is not working as expected.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Filling out this information and **providing logs** will help get the issue resolved faster.

        **Note:** Do not download any files offered in comment responses as malicious users may try to trick you into installing malware.
  - type: dropdown
    id: minecraftVersion
    attributes:
      label: Minecraft Version
      description: What version of Minecraft were you running?
      options:
        - 1.21.3
        - 1.21.1 (LTS)
        - 1.20.1 (LTS)
        - Other (specify below)
    validations:
      required: true
  - type: dropdown
    id: modLoader
    attributes:
      label: Mod Loader
      description: What mod loader were you using?
      options:
        - Forge
        - Fabric
        - NeoForge
    validations:
      required: true
  - type: input
    id: modVersion
    attributes:
      label: Mod Version
      description: What version of the mod were you using?
    validations:
      required: true
  - type: input
    id: balmVersion
    attributes:
      label: Balm Version
      description: What version of Balm were you using? (Try to update Balm if you haven't already!)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Be as thorough as possible and provide a step-by-step guide to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Click this field and drag your latest.log file into it to upload it. You can use also post a link to a site like pastebin, but make sure they are set to not expire.
    validations:
      required: true
  - type: input
    id: optifine
    attributes:
      label: Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?
      description: Specify which and test whether the issue happens with those mods disabled.
